/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlgoView.java
 *
 * Created on 2010-10-24, 00.30.00
 */

package rules.view;

import java.beans.PropertyChangeEvent;
import rules.controller.AlgoController;

/**
 *
 * @author Martynas
 */
public class AlgoView extends AbstractViewPanel {

    private AlgoController controller;
    private String mode;

    /** Creates new form AlgoView */
    public AlgoView(AlgoController controller, String mode) {
        this.controller = controller;
        this.mode = mode;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fcButton = new javax.swing.JRadioButton();
        bcButton = new javax.swing.JRadioButton();
        setAlgo = new javax.swing.JButton();
        oneIteration = new javax.swing.JButton();
        allIterations = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gdb = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        buttonGroup1.add(fcButton);
        fcButton.setSelected(true);
        fcButton.setText("Forward Chaining");
        if (mode.equals("bc")) {
            fcButton.setVisible(false);
        }
        fcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(bcButton);
        bcButton.setText("Backward Chaining");
        if (mode.equals("fc")) {
            bcButton.setVisible(false);
        }
        if (mode.equals("bc")) {
            bcButton.setSelected(true);
        }

        setAlgo.setText("Pradėti iš naujo");
        setAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAlgoActionPerformed(evt);
            }
        });

        oneIteration.setText("Vienas žingsnis");
        oneIteration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneIterationActionPerformed(evt);
            }
        });

        allIterations.setText("Visi žingsniai");
        allIterations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allIterationsActionPerformed(evt);
            }
        });

        gdb.setColumns(10);
        gdb.setFont(new java.awt.Font("Tahoma", 0, 11));
        gdb.setLineWrap(true);
        gdb.setRows(5);
        gdb.setWrapStyleWord(true);
        jScrollPane1.setViewportView(gdb);

        jLabel1.setText("Globali duomenų bazė:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fcButton, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bcButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allIterations, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oneIteration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setAlgo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setAlgo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneIteration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allIterations)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void modelPropertyChange(final PropertyChangeEvent evt) {
        if(evt.getPropertyName().equals(AlgoController.GDB)) {
            gdb.setText((String)evt.getNewValue());
        }
    }

    private void fcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcButtonActionPerformed

    private void setAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAlgoActionPerformed
        if (fcButton.isSelected()) {
            controller.changeAlgoName("Forward");
        }
        else {
            controller.changeAlgoName("Backward");
        }
    }//GEN-LAST:event_setAlgoActionPerformed

    private void oneIterationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneIterationActionPerformed
        controller.changeIterations(1);
    }//GEN-LAST:event_oneIterationActionPerformed

    private void allIterationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allIterationsActionPerformed
        controller.changeIterations(-1);
    }//GEN-LAST:event_allIterationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allIterations;
    private javax.swing.JRadioButton bcButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fcButton;
    private javax.swing.JTextArea gdb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton oneIteration;
    private javax.swing.JButton setAlgo;
    // End of variables declaration//GEN-END:variables

}
